/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddonGiteeAddonSource
 */
export interface AddonGiteeAddonSource {
    /**
     * 
     * @type {string}
     * @memberof AddonGiteeAddonSource
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof AddonGiteeAddonSource
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof AddonGiteeAddonSource
     */
    url?: string;
}

/**
 * Check if a given object implements the AddonGiteeAddonSource interface.
 */
export function instanceOfAddonGiteeAddonSource(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddonGiteeAddonSourceFromJSON(json: any): AddonGiteeAddonSource {
    return AddonGiteeAddonSourceFromJSONTyped(json, false);
}

export function AddonGiteeAddonSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddonGiteeAddonSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': !exists(json, 'path') ? undefined : json['path'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function AddonGiteeAddonSourceToJSON(value?: AddonGiteeAddonSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'token': value.token,
        'url': value.url,
    };
}

