/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddonDeployTo
 */
export interface AddonDeployTo {
    /**
     * 
     * @type {boolean}
     * @memberof AddonDeployTo
     */
    disableControlPlane: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AddonDeployTo
     */
    runtimeCluster: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AddonDeployTo
     */
    runtimeCluster?: boolean;
}

/**
 * Check if a given object implements the AddonDeployTo interface.
 */
export function instanceOfAddonDeployTo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "disableControlPlane" in value;
    isInstance = isInstance && "runtimeCluster" in value;

    return isInstance;
}

export function AddonDeployToFromJSON(json: any): AddonDeployTo {
    return AddonDeployToFromJSONTyped(json, false);
}

export function AddonDeployToFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddonDeployTo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disableControlPlane': json['disableControlPlane'],
        'runtimeCluster': json['runtimeCluster'],
        'runtimeCluster': !exists(json, 'runtime_cluster') ? undefined : json['runtime_cluster'],
    };
}

export function AddonDeployToToJSON(value?: AddonDeployTo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disableControlPlane': value.disableControlPlane,
        'runtimeCluster': value.runtimeCluster,
        'runtime_cluster': value.runtimeCluster,
    };
}

