/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BcodeBcode
 */
export interface BcodeBcode {
    /**
     * 
     * @type {number}
     * @memberof BcodeBcode
     */
    businessCode: number;
    /**
     * 
     * @type {string}
     * @memberof BcodeBcode
     */
    message: string;
}

/**
 * Check if a given object implements the BcodeBcode interface.
 */
export function instanceOfBcodeBcode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "businessCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function BcodeBcodeFromJSON(json: any): BcodeBcode {
    return BcodeBcodeFromJSONTyped(json, false);
}

export function BcodeBcodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BcodeBcode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessCode': json['BusinessCode'],
        'message': json['Message'],
    };
}

export function BcodeBcodeToJSON(value?: BcodeBcode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BusinessCode': value.businessCode,
        'Message': value.message,
    };
}

