/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudproviderCloudCluster
 */
export interface CloudproviderCloudCluster {
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    apiServerURL: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    dashboardURL: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CloudproviderCloudCluster
     */
    labels: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    regionID: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    vpcID: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    zone: string;
    /**
     * 
     * @type {string}
     * @memberof CloudproviderCloudCluster
     */
    zoneID: string;
}

/**
 * Check if a given object implements the CloudproviderCloudCluster interface.
 */
export function instanceOfCloudproviderCloudCluster(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "apiServerURL" in value;
    isInstance = isInstance && "dashboardURL" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "labels" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "provider" in value;
    isInstance = isInstance && "regionID" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "vpcID" in value;
    isInstance = isInstance && "zone" in value;
    isInstance = isInstance && "zoneID" in value;

    return isInstance;
}

export function CloudproviderCloudClusterFromJSON(json: any): CloudproviderCloudCluster {
    return CloudproviderCloudClusterFromJSONTyped(json, false);
}

export function CloudproviderCloudClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudproviderCloudCluster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiServerURL': json['apiServerURL'],
        'dashboardURL': json['dashboardURL'],
        'id': json['id'],
        'labels': json['labels'],
        'name': json['name'],
        'provider': json['provider'],
        'regionID': json['regionID'],
        'status': json['status'],
        'type': json['type'],
        'vpcID': json['vpcID'],
        'zone': json['zone'],
        'zoneID': json['zoneID'],
    };
}

export function CloudproviderCloudClusterToJSON(value?: CloudproviderCloudCluster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiServerURL': value.apiServerURL,
        'dashboardURL': value.dashboardURL,
        'id': value.id,
        'labels': value.labels,
        'name': value.name,
        'provider': value.provider,
        'regionID': value.regionID,
        'status': value.status,
        'type': value.type,
        'vpcID': value.vpcID,
        'zone': value.zone,
        'zoneID': value.zoneID,
    };
}

