/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonCUE
 */
export interface CommonCUE {
    /**
     * 
     * @type {string}
     * @memberof CommonCUE
     */
    template: string;
}

/**
 * Check if a given object implements the CommonCUE interface.
 */
export function instanceOfCommonCUE(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "template" in value;

    return isInstance;
}

export function CommonCUEFromJSON(json: any): CommonCUE {
    return CommonCUEFromJSONTyped(json, false);
}

export function CommonCUEFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonCUE {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': json['template'],
    };
}

export function CommonCUEToJSON(value?: CommonCUE | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': value.template,
    };
}

