/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonPolicyStatus
 */
export interface CommonPolicyStatus {
    /**
     * 
     * @type {string}
     * @memberof CommonPolicyStatus
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommonPolicyStatus
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonPolicyStatus
     */
    type: string;
}

/**
 * Check if a given object implements the CommonPolicyStatus interface.
 */
export function instanceOfCommonPolicyStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CommonPolicyStatusFromJSON(json: any): CommonPolicyStatus {
    return CommonPolicyStatusFromJSONTyped(json, false);
}

export function CommonPolicyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonPolicyStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': json['type'],
    };
}

export function CommonPolicyStatusToJSON(value?: CommonPolicyStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'status': value.status,
        'type': value.type,
    };
}

