/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonApplicationTrait
 */
export interface CommonApplicationTrait {
    /**
     * 
     * @type {string}
     * @memberof CommonApplicationTrait
     */
    properties?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonApplicationTrait
     */
    type: string;
}

/**
 * Check if a given object implements the CommonApplicationTrait interface.
 */
export function instanceOfCommonApplicationTrait(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CommonApplicationTraitFromJSON(json: any): CommonApplicationTrait {
    return CommonApplicationTraitFromJSONTyped(json, false);
}

export function CommonApplicationTraitFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonApplicationTrait {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'type': json['type'],
    };
}

export function CommonApplicationTraitToJSON(value?: CommonApplicationTrait | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'properties': value.properties,
        'type': value.type,
    };
}

