/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonDefinitionReference
 */
export interface CommonDefinitionReference {
    /**
     * 
     * @type {string}
     * @memberof CommonDefinitionReference
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommonDefinitionReference
     */
    version?: string;
}

/**
 * Check if a given object implements the CommonDefinitionReference interface.
 */
export function instanceOfCommonDefinitionReference(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CommonDefinitionReferenceFromJSON(json: any): CommonDefinitionReference {
    return CommonDefinitionReferenceFromJSONTyped(json, false);
}

export function CommonDefinitionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonDefinitionReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function CommonDefinitionReferenceToJSON(value?: CommonDefinitionReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
    };
}

