/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonRevision
 */
export interface CommonRevision {
    /**
     * 
     * @type {string}
     * @memberof CommonRevision
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CommonRevision
     */
    revision: number;
    /**
     * 
     * @type {string}
     * @memberof CommonRevision
     */
    revisionHash?: string;
}

/**
 * Check if a given object implements the CommonRevision interface.
 */
export function instanceOfCommonRevision(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "revision" in value;

    return isInstance;
}

export function CommonRevisionFromJSON(json: any): CommonRevision {
    return CommonRevisionFromJSONTyped(json, false);
}

export function CommonRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'revision': json['revision'],
        'revisionHash': !exists(json, 'revisionHash') ? undefined : json['revisionHash'],
    };
}

export function CommonRevisionToJSON(value?: CommonRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'revision': value.revision,
        'revisionHash': value.revisionHash,
    };
}

