/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigNamespacedName
 */
export interface ConfigNamespacedName {
    /**
     * 
     * @type {string}
     * @memberof ConfigNamespacedName
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigNamespacedName
     */
    namespace: string;
}

/**
 * Check if a given object implements the ConfigNamespacedName interface.
 */
export function instanceOfConfigNamespacedName(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespace" in value;

    return isInstance;
}

export function ConfigNamespacedNameFromJSON(json: any): ConfigNamespacedName {
    return ConfigNamespacedNameFromJSONTyped(json, false);
}

export function ConfigNamespacedNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigNamespacedName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'namespace': json['namespace'],
    };
}

export function ConfigNamespacedNameToJSON(value?: ConfigNamespacedName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'namespace': value.namespace,
    };
}

