/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigClusterTarget
 */
export interface ConfigClusterTarget {
    /**
     * 
     * @type {string}
     * @memberof ConfigClusterTarget
     */
    clusterName: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigClusterTarget
     */
    namespace: string;
}

/**
 * Check if a given object implements the ConfigClusterTarget interface.
 */
export function instanceOfConfigClusterTarget(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clusterName" in value;
    isInstance = isInstance && "namespace" in value;

    return isInstance;
}

export function ConfigClusterTargetFromJSON(json: any): ConfigClusterTarget {
    return ConfigClusterTargetFromJSONTyped(json, false);
}

export function ConfigClusterTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigClusterTarget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clusterName': json['clusterName'],
        'namespace': json['namespace'],
    };
}

export function ConfigClusterTargetToJSON(value?: ConfigClusterTarget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clusterName': value.clusterName,
        'namespace': value.namespace,
    };
}

