/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelBaseModel
 */
export interface ModelBaseModel {
    /**
     * 
     * @type {Date}
     * @memberof ModelBaseModel
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModelBaseModel
     */
    updateTime: Date;
}

/**
 * Check if a given object implements the ModelBaseModel interface.
 */
export function instanceOfModelBaseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function ModelBaseModelFromJSON(json: any): ModelBaseModel {
    return ModelBaseModelFromJSONTyped(json, false);
}

export function ModelBaseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBaseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createTime': (new Date(json['createTime'])),
        'updateTime': (new Date(json['updateTime'])),
    };
}

export function ModelBaseModelToJSON(value?: ModelBaseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createTime': (value.createTime.toISOString()),
        'updateTime': (value.updateTime.toISOString()),
    };
}

