/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelApplicationTrait
 */
export interface ModelApplicationTrait {
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationTrait
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelApplicationTrait
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationTrait
     */
    description: string;
    /**
     * 
     * @type {object}
     * @memberof ModelApplicationTrait
     */
    properties?: object;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationTrait
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelApplicationTrait
     */
    updateTime: Date;
}

/**
 * Check if a given object implements the ModelApplicationTrait interface.
 */
export function instanceOfModelApplicationTrait(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function ModelApplicationTraitFromJSON(json: any): ModelApplicationTrait {
    return ModelApplicationTraitFromJSONTyped(json, false);
}

export function ModelApplicationTraitFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApplicationTrait {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        'description': json['description'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'type': json['type'],
        'updateTime': (new Date(json['updateTime'])),
    };
}

export function ModelApplicationTraitToJSON(value?: ModelApplicationTrait | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'description': value.description,
        'properties': value.properties,
        'type': value.type,
        'updateTime': (value.updateTime.toISOString()),
    };
}

