/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelProjectRef
 */
export interface ModelProjectRef {
    /**
     * 
     * @type {string}
     * @memberof ModelProjectRef
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelProjectRef
     */
    roles: Array<string>;
}

/**
 * Check if a given object implements the ModelProjectRef interface.
 */
export function instanceOfModelProjectRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "roles" in value;

    return isInstance;
}

export function ModelProjectRefFromJSON(json: any): ModelProjectRef {
    return ModelProjectRefFromJSONTyped(json, false);
}

export function ModelProjectRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelProjectRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'roles': json['roles'],
    };
}

export function ModelProjectRefToJSON(value?: ModelProjectRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'roles': value.roles,
    };
}

