/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelCodeInfo } from './ModelCodeInfo';
import {
    ModelCodeInfoFromJSON,
    ModelCodeInfoFromJSONTyped,
    ModelCodeInfoToJSON,
} from './ModelCodeInfo';
import type { ModelImageInfo } from './ModelImageInfo';
import {
    ModelImageInfoFromJSON,
    ModelImageInfoFromJSONTyped,
    ModelImageInfoToJSON,
} from './ModelImageInfo';

/**
 * 
 * @export
 * @interface ModelApplicationRevision
 */
export interface ModelApplicationRevision {
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    appPrimaryKey: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    applyAppConfig?: string;
    /**
     * 
     * @type {ModelCodeInfo}
     * @memberof ModelApplicationRevision
     */
    codeInfo?: ModelCodeInfo;
    /**
     * 
     * @type {Date}
     * @memberof ModelApplicationRevision
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    deployUser: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    envName: string;
    /**
     * 
     * @type {ModelImageInfo}
     * @memberof ModelApplicationRevision
     */
    imageInfo?: ModelImageInfo;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    note: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    revisionCRName: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    rollbackVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    triggerType: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelApplicationRevision
     */
    updateTime: Date;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof ModelApplicationRevision
     */
    workflowName: string;
}

/**
 * Check if a given object implements the ModelApplicationRevision interface.
 */
export function instanceOfModelApplicationRevision(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appPrimaryKey" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "deployUser" in value;
    isInstance = isInstance && "envName" in value;
    isInstance = isInstance && "note" in value;
    isInstance = isInstance && "reason" in value;
    isInstance = isInstance && "revisionCRName" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "triggerType" in value;
    isInstance = isInstance && "updateTime" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "workflowName" in value;

    return isInstance;
}

export function ModelApplicationRevisionFromJSON(json: any): ModelApplicationRevision {
    return ModelApplicationRevisionFromJSONTyped(json, false);
}

export function ModelApplicationRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApplicationRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appPrimaryKey': json['appPrimaryKey'],
        'applyAppConfig': !exists(json, 'applyAppConfig') ? undefined : json['applyAppConfig'],
        'codeInfo': !exists(json, 'codeInfo') ? undefined : ModelCodeInfoFromJSON(json['codeInfo']),
        'createTime': (new Date(json['createTime'])),
        'deployUser': json['deployUser'],
        'envName': json['envName'],
        'imageInfo': !exists(json, 'imageInfo') ? undefined : ModelImageInfoFromJSON(json['imageInfo']),
        'note': json['note'],
        'reason': json['reason'],
        'revisionCRName': json['revisionCRName'],
        'rollbackVersion': !exists(json, 'rollbackVersion') ? undefined : json['rollbackVersion'],
        'status': json['status'],
        'triggerType': json['triggerType'],
        'updateTime': (new Date(json['updateTime'])),
        'version': json['version'],
        'workflowName': json['workflowName'],
    };
}

export function ModelApplicationRevisionToJSON(value?: ModelApplicationRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appPrimaryKey': value.appPrimaryKey,
        'applyAppConfig': value.applyAppConfig,
        'codeInfo': ModelCodeInfoToJSON(value.codeInfo),
        'createTime': (value.createTime.toISOString()),
        'deployUser': value.deployUser,
        'envName': value.envName,
        'imageInfo': ModelImageInfoToJSON(value.imageInfo),
        'note': value.note,
        'reason': value.reason,
        'revisionCRName': value.revisionCRName,
        'rollbackVersion': value.rollbackVersion,
        'status': value.status,
        'triggerType': value.triggerType,
        'updateTime': (value.updateTime.toISOString()),
        'version': value.version,
        'workflowName': value.workflowName,
    };
}

