/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaGroupOption
 */
export interface SchemaGroupOption {
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaGroupOption
     */
    keys: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SchemaGroupOption
     */
    label: string;
}

/**
 * Check if a given object implements the SchemaGroupOption interface.
 */
export function instanceOfSchemaGroupOption(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keys" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function SchemaGroupOptionFromJSON(json: any): SchemaGroupOption {
    return SchemaGroupOptionFromJSONTyped(json, false);
}

export function SchemaGroupOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaGroupOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': json['keys'],
        'label': json['label'],
    };
}

export function SchemaGroupOptionToJSON(value?: SchemaGroupOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys,
        'label': value.label,
    };
}

