/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesWorkspace
 */
export interface TypesWorkspace {
    /**
     * 
     * @type {string}
     * @memberof TypesWorkspace
     */
    name: string;
}

/**
 * Check if a given object implements the TypesWorkspace interface.
 */
export function instanceOfTypesWorkspace(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TypesWorkspaceFromJSON(json: any): TypesWorkspace {
    return TypesWorkspaceFromJSONTyped(json, false);
}

export function TypesWorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesWorkspace {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TypesWorkspaceToJSON(value?: TypesWorkspace | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

