/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesKubernetesService
 */
export interface TypesKubernetesService {
    /**
     * 
     * @type {string}
     * @memberof TypesKubernetesService
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TypesKubernetesService
     */
    namespace: string;
    /**
     * 
     * @type {number}
     * @memberof TypesKubernetesService
     */
    port: number;
}

/**
 * Check if a given object implements the TypesKubernetesService interface.
 */
export function instanceOfTypesKubernetesService(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespace" in value;
    isInstance = isInstance && "port" in value;

    return isInstance;
}

export function TypesKubernetesServiceFromJSON(json: any): TypesKubernetesService {
    return TypesKubernetesServiceFromJSONTyped(json, false);
}

export function TypesKubernetesServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesKubernetesService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'namespace': json['namespace'],
        'port': json['port'],
    };
}

export function TypesKubernetesServiceToJSON(value?: TypesKubernetesService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'namespace': value.namespace,
        'port': value.port,
    };
}

