/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesNamespacedName
 */
export interface TypesNamespacedName {
    /**
     * 
     * @type {string}
     * @memberof TypesNamespacedName
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TypesNamespacedName
     */
    namespace: string;
}

/**
 * Check if a given object implements the TypesNamespacedName interface.
 */
export function instanceOfTypesNamespacedName(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespace" in value;

    return isInstance;
}

export function TypesNamespacedNameFromJSON(json: any): TypesNamespacedName {
    return TypesNamespacedNameFromJSONTyped(json, false);
}

export function TypesNamespacedNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesNamespacedName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'namespace': json['Namespace'],
    };
}

export function TypesNamespacedNameToJSON(value?: TypesNamespacedName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Namespace': value.namespace,
    };
}

