/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesLogos
 */
export interface TypesLogos {
    /**
     * 
     * @type {string}
     * @memberof TypesLogos
     */
    large: string;
    /**
     * 
     * @type {string}
     * @memberof TypesLogos
     */
    small: string;
}

/**
 * Check if a given object implements the TypesLogos interface.
 */
export function instanceOfTypesLogos(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "large" in value;
    isInstance = isInstance && "small" in value;

    return isInstance;
}

export function TypesLogosFromJSON(json: any): TypesLogos {
    return TypesLogosFromJSONTyped(json, false);
}

export function TypesLogosFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesLogos {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'large': json['large'],
        'small': json['small'],
    };
}

export function TypesLogosToJSON(value?: TypesLogos | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'large': value.large,
        'small': value.small,
    };
}

