/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AddonDefinition
 */
export interface V1AddonDefinition {
    /**
     * 
     * @type {string}
     * @memberof V1AddonDefinition
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AddonDefinition
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AddonDefinition
     */
    type?: string;
}

/**
 * Check if a given object implements the V1AddonDefinition interface.
 */
export function instanceOfV1AddonDefinition(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1AddonDefinitionFromJSON(json: any): V1AddonDefinition {
    return V1AddonDefinitionFromJSONTyped(json, false);
}

export function V1AddonDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AddonDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function V1AddonDefinitionToJSON(value?: V1AddonDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'type': value.type,
    };
}

