/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1alpha1InputItem } from './V1alpha1InputItem';
import {
    V1alpha1InputItemFromJSON,
    V1alpha1InputItemFromJSONTyped,
    V1alpha1InputItemToJSON,
} from './V1alpha1InputItem';
import type { V1alpha1OutputItem } from './V1alpha1OutputItem';
import {
    V1alpha1OutputItemFromJSON,
    V1alpha1OutputItemFromJSONTyped,
    V1alpha1OutputItemToJSON,
} from './V1alpha1OutputItem';
import type { V1alpha1WorkflowStepBase } from './V1alpha1WorkflowStepBase';
import {
    V1alpha1WorkflowStepBaseFromJSON,
    V1alpha1WorkflowStepBaseFromJSONTyped,
    V1alpha1WorkflowStepBaseToJSON,
} from './V1alpha1WorkflowStepBase';
import type { V1alpha1WorkflowStepMeta } from './V1alpha1WorkflowStepMeta';
import {
    V1alpha1WorkflowStepMetaFromJSON,
    V1alpha1WorkflowStepMetaFromJSONTyped,
    V1alpha1WorkflowStepMetaToJSON,
} from './V1alpha1WorkflowStepMeta';

/**
 * 
 * @export
 * @interface V1alpha1WorkflowStep
 */
export interface V1alpha1WorkflowStep {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1alpha1WorkflowStep
     */
    dependsOn?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    _if?: string;
    /**
     * 
     * @type {Array<V1alpha1InputItem>}
     * @memberof V1alpha1WorkflowStep
     */
    inputs?: Array<V1alpha1InputItem>;
    /**
     * 
     * @type {V1alpha1WorkflowStepMeta}
     * @memberof V1alpha1WorkflowStep
     */
    meta?: V1alpha1WorkflowStepMeta;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    name?: string;
    /**
     * 
     * @type {Array<V1alpha1OutputItem>}
     * @memberof V1alpha1WorkflowStep
     */
    outputs?: Array<V1alpha1OutputItem>;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    properties?: string;
    /**
     * 
     * @type {Array<V1alpha1WorkflowStepBase>}
     * @memberof V1alpha1WorkflowStep
     */
    subSteps?: Array<V1alpha1WorkflowStepBase>;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    timeout?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkflowStep
     */
    type: string;
}

/**
 * Check if a given object implements the V1alpha1WorkflowStep interface.
 */
export function instanceOfV1alpha1WorkflowStep(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function V1alpha1WorkflowStepFromJSON(json: any): V1alpha1WorkflowStep {
    return V1alpha1WorkflowStepFromJSONTyped(json, false);
}

export function V1alpha1WorkflowStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1WorkflowStep {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dependsOn': !exists(json, 'dependsOn') ? undefined : json['dependsOn'],
        '_if': !exists(json, 'if') ? undefined : json['if'],
        'inputs': !exists(json, 'inputs') ? undefined : ((json['inputs'] as Array<any>).map(V1alpha1InputItemFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : V1alpha1WorkflowStepMetaFromJSON(json['meta']),
        'mode': !exists(json, 'mode') ? undefined : json['mode'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'outputs': !exists(json, 'outputs') ? undefined : ((json['outputs'] as Array<any>).map(V1alpha1OutputItemFromJSON)),
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'subSteps': !exists(json, 'subSteps') ? undefined : ((json['subSteps'] as Array<any>).map(V1alpha1WorkflowStepBaseFromJSON)),
        'timeout': !exists(json, 'timeout') ? undefined : json['timeout'],
        'type': json['type'],
    };
}

export function V1alpha1WorkflowStepToJSON(value?: V1alpha1WorkflowStep | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dependsOn': value.dependsOn,
        'if': value._if,
        'inputs': value.inputs === undefined ? undefined : ((value.inputs as Array<any>).map(V1alpha1InputItemToJSON)),
        'meta': V1alpha1WorkflowStepMetaToJSON(value.meta),
        'mode': value.mode,
        'name': value.name,
        'outputs': value.outputs === undefined ? undefined : ((value.outputs as Array<any>).map(V1alpha1OutputItemToJSON)),
        'properties': value.properties,
        'subSteps': value.subSteps === undefined ? undefined : ((value.subSteps as Array<any>).map(V1alpha1WorkflowStepBaseToJSON)),
        'timeout': value.timeout,
        'type': value.type,
    };
}

