/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1alpha1InputItem
 */
export interface V1alpha1InputItem {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1InputItem
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1InputItem
     */
    parameterKey?: string;
}

/**
 * Check if a given object implements the V1alpha1InputItem interface.
 */
export function instanceOfV1alpha1InputItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;

    return isInstance;
}

export function V1alpha1InputItemFromJSON(json: any): V1alpha1InputItem {
    return V1alpha1InputItemFromJSONTyped(json, false);
}

export function V1alpha1InputItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1InputItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': json['from'],
        'parameterKey': !exists(json, 'parameterKey') ? undefined : json['parameterKey'],
    };
}

export function V1alpha1InputItemToJSON(value?: V1alpha1InputItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'parameterKey': value.parameterKey,
    };
}

