/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AppCompareResponse
 */
export interface V1AppCompareResponse {
    /**
     * 
     * @type {string}
     * @memberof V1AppCompareResponse
     */
    baseAppYAML: string;
    /**
     * 
     * @type {string}
     * @memberof V1AppCompareResponse
     */
    diffReport: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1AppCompareResponse
     */
    isDiff: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1AppCompareResponse
     */
    targetAppYAML: string;
}

/**
 * Check if a given object implements the V1AppCompareResponse interface.
 */
export function instanceOfV1AppCompareResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "baseAppYAML" in value;
    isInstance = isInstance && "diffReport" in value;
    isInstance = isInstance && "isDiff" in value;
    isInstance = isInstance && "targetAppYAML" in value;

    return isInstance;
}

export function V1AppCompareResponseFromJSON(json: any): V1AppCompareResponse {
    return V1AppCompareResponseFromJSONTyped(json, false);
}

export function V1AppCompareResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AppCompareResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'baseAppYAML': json['baseAppYAML'],
        'diffReport': json['diffReport'],
        'isDiff': json['isDiff'],
        'targetAppYAML': json['targetAppYAML'],
    };
}

export function V1AppCompareResponseToJSON(value?: V1AppCompareResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'baseAppYAML': value.baseAppYAML,
        'diffReport': value.diffReport,
        'isDiff': value.isDiff,
        'targetAppYAML': value.targetAppYAML,
    };
}

