/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AppDryRunResponse
 */
export interface V1AppDryRunResponse {
    /**
     * 
     * @type {string}
     * @memberof V1AppDryRunResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1AppDryRunResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1AppDryRunResponse
     */
    yaml: string;
}

/**
 * Check if a given object implements the V1AppDryRunResponse interface.
 */
export function instanceOfV1AppDryRunResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "yaml" in value;

    return isInstance;
}

export function V1AppDryRunResponseFromJSON(json: any): V1AppDryRunResponse {
    return V1AppDryRunResponseFromJSONTyped(json, false);
}

export function V1AppDryRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AppDryRunResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'success': json['success'],
        'yaml': json['yaml'],
    };
}

export function V1AppDryRunResponseToJSON(value?: V1AppDryRunResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'success': value.success,
        'yaml': value.yaml,
    };
}

