/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1alpha1WorkflowExecuteMode } from './V1alpha1WorkflowExecuteMode';
import {
    V1alpha1WorkflowExecuteModeFromJSON,
    V1alpha1WorkflowExecuteModeFromJSONTyped,
    V1alpha1WorkflowExecuteModeToJSON,
} from './V1alpha1WorkflowExecuteMode';
import type { V1alpha1WorkflowStep } from './V1alpha1WorkflowStep';
import {
    V1alpha1WorkflowStepFromJSON,
    V1alpha1WorkflowStepFromJSONTyped,
    V1alpha1WorkflowStepToJSON,
} from './V1alpha1WorkflowStep';

/**
 * 
 * @export
 * @interface V1beta1Workflow
 */
export interface V1beta1Workflow {
    /**
     * 
     * @type {V1alpha1WorkflowExecuteMode}
     * @memberof V1beta1Workflow
     */
    mode?: V1alpha1WorkflowExecuteMode;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Workflow
     */
    ref?: string;
    /**
     * 
     * @type {Array<V1alpha1WorkflowStep>}
     * @memberof V1beta1Workflow
     */
    steps?: Array<V1alpha1WorkflowStep>;
}

/**
 * Check if a given object implements the V1beta1Workflow interface.
 */
export function instanceOfV1beta1Workflow(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta1WorkflowFromJSON(json: any): V1beta1Workflow {
    return V1beta1WorkflowFromJSONTyped(json, false);
}

export function V1beta1WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1Workflow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': !exists(json, 'mode') ? undefined : V1alpha1WorkflowExecuteModeFromJSON(json['mode']),
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'steps': !exists(json, 'steps') ? undefined : ((json['steps'] as Array<any>).map(V1alpha1WorkflowStepFromJSON)),
    };
}

export function V1beta1WorkflowToJSON(value?: V1beta1Workflow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': V1alpha1WorkflowExecuteModeToJSON(value.mode),
        'ref': value.ref,
        'steps': value.steps === undefined ? undefined : ((value.steps as Array<any>).map(V1alpha1WorkflowStepToJSON)),
    };
}

