/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonDefinitionReference } from './CommonDefinitionReference';
import {
    CommonDefinitionReferenceFromJSON,
    CommonDefinitionReferenceFromJSONTyped,
    CommonDefinitionReferenceToJSON,
} from './CommonDefinitionReference';
import type { CommonSchematic } from './CommonSchematic';
import {
    CommonSchematicFromJSON,
    CommonSchematicFromJSONTyped,
    CommonSchematicToJSON,
} from './CommonSchematic';

/**
 * 
 * @export
 * @interface V1beta1PolicyDefinitionSpec
 */
export interface V1beta1PolicyDefinitionSpec {
    /**
     * 
     * @type {CommonDefinitionReference}
     * @memberof V1beta1PolicyDefinitionSpec
     */
    definitionRef?: CommonDefinitionReference;
    /**
     * 
     * @type {boolean}
     * @memberof V1beta1PolicyDefinitionSpec
     */
    manageHealthCheck?: boolean;
    /**
     * 
     * @type {CommonSchematic}
     * @memberof V1beta1PolicyDefinitionSpec
     */
    schematic?: CommonSchematic;
}

/**
 * Check if a given object implements the V1beta1PolicyDefinitionSpec interface.
 */
export function instanceOfV1beta1PolicyDefinitionSpec(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta1PolicyDefinitionSpecFromJSON(json: any): V1beta1PolicyDefinitionSpec {
    return V1beta1PolicyDefinitionSpecFromJSONTyped(json, false);
}

export function V1beta1PolicyDefinitionSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1PolicyDefinitionSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'definitionRef': !exists(json, 'definitionRef') ? undefined : CommonDefinitionReferenceFromJSON(json['definitionRef']),
        'manageHealthCheck': !exists(json, 'manageHealthCheck') ? undefined : json['manageHealthCheck'],
        'schematic': !exists(json, 'schematic') ? undefined : CommonSchematicFromJSON(json['schematic']),
    };
}

export function V1beta1PolicyDefinitionSpecToJSON(value?: V1beta1PolicyDefinitionSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definitionRef': CommonDefinitionReferenceToJSON(value.definitionRef),
        'manageHealthCheck': value.manageHealthCheck,
        'schematic': CommonSchematicToJSON(value.schematic),
    };
}

