/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RepoChartVersion } from './RepoChartVersion';
import {
    RepoChartVersionFromJSON,
    RepoChartVersionFromJSONTyped,
    RepoChartVersionToJSON,
} from './RepoChartVersion';

/**
 * 
 * @export
 * @interface V1ChartVersionListResponse
 */
export interface V1ChartVersionListResponse {
    /**
     * 
     * @type {Array<RepoChartVersion>}
     * @memberof V1ChartVersionListResponse
     */
    versions: Array<RepoChartVersion>;
}

/**
 * Check if a given object implements the V1ChartVersionListResponse interface.
 */
export function instanceOfV1ChartVersionListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "versions" in value;

    return isInstance;
}

export function V1ChartVersionListResponseFromJSON(json: any): V1ChartVersionListResponse {
    return V1ChartVersionListResponseFromJSONTyped(json, false);
}

export function V1ChartVersionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ChartVersionListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versions': ((json['versions'] as Array<any>).map(RepoChartVersionFromJSON)),
    };
}

export function V1ChartVersionListResponseToJSON(value?: V1ChartVersionListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'versions': ((value.versions as Array<any>).map(RepoChartVersionToJSON)),
    };
}

