/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ComponentSelector
 */
export interface V1ComponentSelector {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ComponentSelector
     */
    components: Array<string>;
}

/**
 * Check if a given object implements the V1ComponentSelector interface.
 */
export function instanceOfV1ComponentSelector(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "components" in value;

    return isInstance;
}

export function V1ComponentSelectorFromJSON(json: any): V1ComponentSelector {
    return V1ComponentSelectorFromJSONTyped(json, false);
}

export function V1ComponentSelectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ComponentSelector {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'components': json['components'],
    };
}

export function V1ComponentSelectorToJSON(value?: V1ComponentSelector | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'components': value.components,
    };
}

