/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateClusterRequest
 */
export interface V1CreateClusterRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    dashboardURL?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    kubeConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    kubeConfigSecret?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1CreateClusterRequest
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof V1CreateClusterRequest
     */
    name: string;
}

/**
 * Check if a given object implements the V1CreateClusterRequest interface.
 */
export function instanceOfV1CreateClusterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "icon" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function V1CreateClusterRequestFromJSON(json: any): V1CreateClusterRequest {
    return V1CreateClusterRequestFromJSONTyped(json, false);
}

export function V1CreateClusterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateClusterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'dashboardURL': !exists(json, 'dashboardURL') ? undefined : json['dashboardURL'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'icon': json['icon'],
        'kubeConfig': !exists(json, 'kubeConfig') ? undefined : json['kubeConfig'],
        'kubeConfigSecret': !exists(json, 'kubeConfigSecret') ? undefined : json['kubeConfigSecret'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'name': json['name'],
    };
}

export function V1CreateClusterRequestToJSON(value?: V1CreateClusterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'dashboardURL': value.dashboardURL,
        'description': value.description,
        'icon': value.icon,
        'kubeConfig': value.kubeConfig,
        'kubeConfigSecret': value.kubeConfigSecret,
        'labels': value.labels,
        'name': value.name,
    };
}

