/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ClusterTarget } from './V1ClusterTarget';
import {
    V1ClusterTargetFromJSON,
    V1ClusterTargetFromJSONTyped,
    V1ClusterTargetToJSON,
} from './V1ClusterTarget';

/**
 * 
 * @export
 * @interface V1CreateTargetRequest
 */
export interface V1CreateTargetRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateTargetRequest
     */
    alias?: string;
    /**
     * 
     * @type {V1ClusterTarget}
     * @memberof V1CreateTargetRequest
     */
    cluster?: V1ClusterTarget;
    /**
     * 
     * @type {string}
     * @memberof V1CreateTargetRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateTargetRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateTargetRequest
     */
    project: string;
    /**
     * 
     * @type {object}
     * @memberof V1CreateTargetRequest
     */
    variable?: object;
}

/**
 * Check if a given object implements the V1CreateTargetRequest interface.
 */
export function instanceOfV1CreateTargetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "project" in value;

    return isInstance;
}

export function V1CreateTargetRequestFromJSON(json: any): V1CreateTargetRequest {
    return V1CreateTargetRequestFromJSONTyped(json, false);
}

export function V1CreateTargetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateTargetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'cluster': !exists(json, 'cluster') ? undefined : V1ClusterTargetFromJSON(json['cluster']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'project': json['project'],
        'variable': !exists(json, 'variable') ? undefined : json['variable'],
    };
}

export function V1CreateTargetRequestToJSON(value?: V1CreateTargetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'cluster': V1ClusterTargetToJSON(value.cluster),
        'description': value.description,
        'name': value.name,
        'project': value.project,
        'variable': value.variable,
    };
}

