/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateApplicationTriggerRequest
 */
export interface V1CreateApplicationTriggerRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    componentName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    payloadType: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    registry?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateApplicationTriggerRequest
     */
    workflowName: string;
}

/**
 * Check if a given object implements the V1CreateApplicationTriggerRequest interface.
 */
export function instanceOfV1CreateApplicationTriggerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "payloadType" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "workflowName" in value;

    return isInstance;
}

export function V1CreateApplicationTriggerRequestFromJSON(json: any): V1CreateApplicationTriggerRequest {
    return V1CreateApplicationTriggerRequestFromJSONTyped(json, false);
}

export function V1CreateApplicationTriggerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateApplicationTriggerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'componentName': !exists(json, 'componentName') ? undefined : json['componentName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'payloadType': json['payloadType'],
        'registry': !exists(json, 'registry') ? undefined : json['registry'],
        'type': json['type'],
        'workflowName': json['workflowName'],
    };
}

export function V1CreateApplicationTriggerRequestToJSON(value?: V1CreateApplicationTriggerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'componentName': value.componentName,
        'description': value.description,
        'name': value.name,
        'payloadType': value.payloadType,
        'registry': value.registry,
        'type': value.type,
        'workflowName': value.workflowName,
    };
}

