/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1WorkflowPolicyBinding } from './V1WorkflowPolicyBinding';
import {
    V1WorkflowPolicyBindingFromJSON,
    V1WorkflowPolicyBindingFromJSONTyped,
    V1WorkflowPolicyBindingToJSON,
} from './V1WorkflowPolicyBinding';

/**
 * 
 * @export
 * @interface V1DetailPolicyResponse
 */
export interface V1DetailPolicyResponse {
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailPolicyResponse
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    creator: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    envName: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof V1DetailPolicyResponse
     */
    properties: object;
    /**
     * 
     * @type {string}
     * @memberof V1DetailPolicyResponse
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailPolicyResponse
     */
    updateTime: Date;
    /**
     * 
     * @type {Array<V1WorkflowPolicyBinding>}
     * @memberof V1DetailPolicyResponse
     */
    workflowPolicyBind?: Array<V1WorkflowPolicyBinding>;
}

/**
 * Check if a given object implements the V1DetailPolicyResponse interface.
 */
export function instanceOfV1DetailPolicyResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "creator" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "envName" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "properties" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function V1DetailPolicyResponseFromJSON(json: any): V1DetailPolicyResponse {
    return V1DetailPolicyResponseFromJSONTyped(json, false);
}

export function V1DetailPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DetailPolicyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        'creator': json['creator'],
        'description': json['description'],
        'envName': json['envName'],
        'name': json['name'],
        'properties': json['properties'],
        'type': json['type'],
        'updateTime': (new Date(json['updateTime'])),
        'workflowPolicyBind': !exists(json, 'workflowPolicyBind') ? undefined : ((json['workflowPolicyBind'] as Array<any>).map(V1WorkflowPolicyBindingFromJSON)),
    };
}

export function V1DetailPolicyResponseToJSON(value?: V1DetailPolicyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'creator': value.creator,
        'description': value.description,
        'envName': value.envName,
        'name': value.name,
        'properties': value.properties,
        'type': value.type,
        'updateTime': (value.updateTime.toISOString()),
        'workflowPolicyBind': value.workflowPolicyBind === undefined ? undefined : ((value.workflowPolicyBind as Array<any>).map(V1WorkflowPolicyBindingToJSON)),
    };
}

