/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelWorkflowStepStatus } from './ModelWorkflowStepStatus';
import {
    ModelWorkflowStepStatusFromJSON,
    ModelWorkflowStepStatusFromJSONTyped,
    ModelWorkflowStepStatusToJSON,
} from './ModelWorkflowStepStatus';

/**
 * 
 * @export
 * @interface V1DetailWorkflowRecordResponse
 */
export interface V1DetailWorkflowRecordResponse {
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    applicationRevision: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailWorkflowRecordResponse
     */
    deployTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    deployUser: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailWorkflowRecordResponse
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    namespace: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    note: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailWorkflowRecordResponse
     */
    startTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    status: string;
    /**
     * 
     * @type {Array<ModelWorkflowStepStatus>}
     * @memberof V1DetailWorkflowRecordResponse
     */
    steps?: Array<ModelWorkflowStepStatus>;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    triggerType: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    workflowAlias: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowRecordResponse
     */
    workflowName: string;
}

/**
 * Check if a given object implements the V1DetailWorkflowRecordResponse interface.
 */
export function instanceOfV1DetailWorkflowRecordResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "applicationRevision" in value;
    isInstance = isInstance && "deployTime" in value;
    isInstance = isInstance && "deployUser" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "mode" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespace" in value;
    isInstance = isInstance && "note" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "triggerType" in value;
    isInstance = isInstance && "workflowAlias" in value;
    isInstance = isInstance && "workflowName" in value;

    return isInstance;
}

export function V1DetailWorkflowRecordResponseFromJSON(json: any): V1DetailWorkflowRecordResponse {
    return V1DetailWorkflowRecordResponseFromJSONTyped(json, false);
}

export function V1DetailWorkflowRecordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DetailWorkflowRecordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'applicationRevision': json['applicationRevision'],
        'deployTime': (new Date(json['deployTime'])),
        'deployUser': json['deployUser'],
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'message': json['message'],
        'mode': json['mode'],
        'name': json['name'],
        'namespace': json['namespace'],
        'note': json['note'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'status': json['status'],
        'steps': !exists(json, 'steps') ? undefined : ((json['steps'] as Array<any>).map(ModelWorkflowStepStatusFromJSON)),
        'triggerType': json['triggerType'],
        'workflowAlias': json['workflowAlias'],
        'workflowName': json['workflowName'],
    };
}

export function V1DetailWorkflowRecordResponseToJSON(value?: V1DetailWorkflowRecordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'applicationRevision': value.applicationRevision,
        'deployTime': (value.deployTime.toISOString()),
        'deployUser': value.deployUser,
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'message': value.message,
        'mode': value.mode,
        'name': value.name,
        'namespace': value.namespace,
        'note': value.note,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'status': value.status,
        'steps': value.steps === undefined ? undefined : ((value.steps as Array<any>).map(ModelWorkflowStepStatusToJSON)),
        'triggerType': value.triggerType,
        'workflowAlias': value.workflowAlias,
        'workflowName': value.workflowName,
    };
}

