/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1WorkflowStep } from './V1WorkflowStep';
import {
    V1WorkflowStepFromJSON,
    V1WorkflowStepFromJSONTyped,
    V1WorkflowStepToJSON,
} from './V1WorkflowStep';

/**
 * 
 * @export
 * @interface V1DetailWorkflowResponse
 */
export interface V1DetailWorkflowResponse {
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailWorkflowResponse
     */
    createTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof V1DetailWorkflowResponse
     */
    _default: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1DetailWorkflowResponse
     */
    enable: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    envName: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    name: string;
    /**
     * 
     * @type {Array<V1WorkflowStep>}
     * @memberof V1DetailWorkflowResponse
     */
    steps?: Array<V1WorkflowStep>;
    /**
     * 
     * @type {string}
     * @memberof V1DetailWorkflowResponse
     */
    subMode: string;
    /**
     * 
     * @type {Date}
     * @memberof V1DetailWorkflowResponse
     */
    updateTime: Date;
}

/**
 * Check if a given object implements the V1DetailWorkflowResponse interface.
 */
export function instanceOfV1DetailWorkflowResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "_default" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "enable" in value;
    isInstance = isInstance && "envName" in value;
    isInstance = isInstance && "mode" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "subMode" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function V1DetailWorkflowResponseFromJSON(json: any): V1DetailWorkflowResponse {
    return V1DetailWorkflowResponseFromJSONTyped(json, false);
}

export function V1DetailWorkflowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DetailWorkflowResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        '_default': json['default'],
        'description': json['description'],
        'enable': json['enable'],
        'envName': json['envName'],
        'mode': json['mode'],
        'name': json['name'],
        'steps': !exists(json, 'steps') ? undefined : ((json['steps'] as Array<any>).map(V1WorkflowStepFromJSON)),
        'subMode': json['subMode'],
        'updateTime': (new Date(json['updateTime'])),
    };
}

export function V1DetailWorkflowResponseToJSON(value?: V1DetailWorkflowResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'default': value._default,
        'description': value.description,
        'enable': value.enable,
        'envName': value.envName,
        'mode': value.mode,
        'name': value.name,
        'steps': value.steps === undefined ? undefined : ((value.steps as Array<any>).map(V1WorkflowStepToJSON)),
        'subMode': value.subMode,
        'updateTime': (value.updateTime.toISOString()),
    };
}

