/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1EnvBinding
 */
export interface V1EnvBinding {
    /**
     * 
     * @type {string}
     * @memberof V1EnvBinding
     */
    name: string;
}

/**
 * Check if a given object implements the V1EnvBinding interface.
 */
export function instanceOfV1EnvBinding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function V1EnvBindingFromJSON(json: any): V1EnvBinding {
    return V1EnvBindingFromJSONTyped(json, false);
}

export function V1EnvBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1EnvBinding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function V1EnvBindingToJSON(value?: V1EnvBinding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

