/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetPipelineRunLogResponse
 */
export interface V1GetPipelineRunLogResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    log: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    phase: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineRunLogResponse
     */
    type: string;
}

/**
 * Check if a given object implements the V1GetPipelineRunLogResponse interface.
 */
export function instanceOfV1GetPipelineRunLogResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "log" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "phase" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function V1GetPipelineRunLogResponseFromJSON(json: any): V1GetPipelineRunLogResponse {
    return V1GetPipelineRunLogResponseFromJSONTyped(json, false);
}

export function V1GetPipelineRunLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetPipelineRunLogResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'log': json['log'],
        'name': json['name'],
        'phase': json['phase'],
        'source': json['source'],
        'type': json['type'],
    };
}

export function V1GetPipelineRunLogResponseToJSON(value?: V1GetPipelineRunLogResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'log': value.log,
        'name': value.name,
        'phase': value.phase,
        'source': value.source,
        'type': value.type,
    };
}

