/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelWorkflowSpec } from './ModelWorkflowSpec';
import {
    ModelWorkflowSpecFromJSON,
    ModelWorkflowSpecFromJSONTyped,
    ModelWorkflowSpecToJSON,
} from './ModelWorkflowSpec';
import type { V1NameAlias } from './V1NameAlias';
import {
    V1NameAliasFromJSON,
    V1NameAliasFromJSONTyped,
    V1NameAliasToJSON,
} from './V1NameAlias';
import type { V1PipelineInfo } from './V1PipelineInfo';
import {
    V1PipelineInfoFromJSON,
    V1PipelineInfoFromJSONTyped,
    V1PipelineInfoToJSON,
} from './V1PipelineInfo';

/**
 * 
 * @export
 * @interface V1GetPipelineResponse
 */
export interface V1GetPipelineResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineResponse
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof V1GetPipelineResponse
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineResponse
     */
    description: string;
    /**
     * 
     * @type {V1PipelineInfo}
     * @memberof V1GetPipelineResponse
     */
    info: V1PipelineInfo;
    /**
     * 
     * @type {string}
     * @memberof V1GetPipelineResponse
     */
    name: string;
    /**
     * 
     * @type {V1NameAlias}
     * @memberof V1GetPipelineResponse
     */
    project: V1NameAlias;
    /**
     * 
     * @type {ModelWorkflowSpec}
     * @memberof V1GetPipelineResponse
     */
    spec: ModelWorkflowSpec;
}

/**
 * Check if a given object implements the V1GetPipelineResponse interface.
 */
export function instanceOfV1GetPipelineResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "info" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "project" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function V1GetPipelineResponseFromJSON(json: any): V1GetPipelineResponse {
    return V1GetPipelineResponseFromJSONTyped(json, false);
}

export function V1GetPipelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetPipelineResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        'description': json['description'],
        'info': V1PipelineInfoFromJSON(json['info']),
        'name': json['name'],
        'project': V1NameAliasFromJSON(json['project']),
        'spec': ModelWorkflowSpecFromJSON(json['spec']),
    };
}

export function V1GetPipelineResponseToJSON(value?: V1GetPipelineResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'description': value.description,
        'info': V1PipelineInfoToJSON(value.info),
        'name': value.name,
        'project': V1NameAliasToJSON(value.project),
        'spec': ModelWorkflowSpecToJSON(value.spec),
    };
}

