/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1History
 */
export interface V1History {
    /**
     * 
     * @type {string}
     * @memberof V1History
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof V1History
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof V1History
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof V1History
     */
    createdBy?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1History
     */
    emptyLayer?: boolean;
}

/**
 * Check if a given object implements the V1History interface.
 */
export function instanceOfV1History(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1HistoryFromJSON(json: any): V1History {
    return V1HistoryFromJSONTyped(json, false);
}

export function V1HistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1History {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'emptyLayer': !exists(json, 'empty_layer') ? undefined : json['empty_layer'],
    };
}

export function V1HistoryToJSON(value?: V1History | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'comment': value.comment,
        'created': value.created,
        'created_by': value.createdBy,
        'empty_layer': value.emptyLayer,
    };
}

