/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1InitAdminResponse
 */
export interface V1InitAdminResponse {
    /**
     * 
     * @type {boolean}
     * @memberof V1InitAdminResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the V1InitAdminResponse interface.
 */
export function instanceOfV1InitAdminResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function V1InitAdminResponseFromJSON(json: any): V1InitAdminResponse {
    return V1InitAdminResponseFromJSONTyped(json, false);
}

export function V1InitAdminResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1InitAdminResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function V1InitAdminResponseToJSON(value?: V1InitAdminResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

