/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1AddonRegistry } from './V1AddonRegistry';
import {
    V1AddonRegistryFromJSON,
    V1AddonRegistryFromJSONTyped,
    V1AddonRegistryToJSON,
} from './V1AddonRegistry';

/**
 * 
 * @export
 * @interface V1ListAddonRegistryResponse
 */
export interface V1ListAddonRegistryResponse {
    /**
     * 
     * @type {Array<V1AddonRegistry>}
     * @memberof V1ListAddonRegistryResponse
     */
    registries: Array<V1AddonRegistry>;
}

/**
 * Check if a given object implements the V1ListAddonRegistryResponse interface.
 */
export function instanceOfV1ListAddonRegistryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "registries" in value;

    return isInstance;
}

export function V1ListAddonRegistryResponseFromJSON(json: any): V1ListAddonRegistryResponse {
    return V1ListAddonRegistryResponseFromJSONTyped(json, false);
}

export function V1ListAddonRegistryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListAddonRegistryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'registries': ((json['registries'] as Array<any>).map(V1AddonRegistryFromJSON)),
    };
}

export function V1ListAddonRegistryResponseToJSON(value?: V1ListAddonRegistryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'registries': ((value.registries as Array<any>).map(V1AddonRegistryToJSON)),
    };
}

