/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ApplicationBase } from './V1ApplicationBase';
import {
    V1ApplicationBaseFromJSON,
    V1ApplicationBaseFromJSONTyped,
    V1ApplicationBaseToJSON,
} from './V1ApplicationBase';

/**
 * 
 * @export
 * @interface V1ListApplicationResponse
 */
export interface V1ListApplicationResponse {
    /**
     * 
     * @type {Array<V1ApplicationBase>}
     * @memberof V1ListApplicationResponse
     */
    applications: Array<V1ApplicationBase>;
}

/**
 * Check if a given object implements the V1ListApplicationResponse interface.
 */
export function instanceOfV1ListApplicationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "applications" in value;

    return isInstance;
}

export function V1ListApplicationResponseFromJSON(json: any): V1ListApplicationResponse {
    return V1ListApplicationResponseFromJSONTyped(json, false);
}

export function V1ListApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListApplicationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'applications': ((json['applications'] as Array<any>).map(V1ApplicationBaseFromJSON)),
    };
}

export function V1ListApplicationResponseToJSON(value?: V1ListApplicationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'applications': ((value.applications as Array<any>).map(V1ApplicationBaseToJSON)),
    };
}

