/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1CreateCloudClusterResponse } from './V1CreateCloudClusterResponse';
import {
    V1CreateCloudClusterResponseFromJSON,
    V1CreateCloudClusterResponseFromJSONTyped,
    V1CreateCloudClusterResponseToJSON,
} from './V1CreateCloudClusterResponse';

/**
 * 
 * @export
 * @interface V1ListCloudClusterCreationResponse
 */
export interface V1ListCloudClusterCreationResponse {
    /**
     * 
     * @type {Array<V1CreateCloudClusterResponse>}
     * @memberof V1ListCloudClusterCreationResponse
     */
    creations: Array<V1CreateCloudClusterResponse>;
}

/**
 * Check if a given object implements the V1ListCloudClusterCreationResponse interface.
 */
export function instanceOfV1ListCloudClusterCreationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "creations" in value;

    return isInstance;
}

export function V1ListCloudClusterCreationResponseFromJSON(json: any): V1ListCloudClusterCreationResponse {
    return V1ListCloudClusterCreationResponseFromJSONTyped(json, false);
}

export function V1ListCloudClusterCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListCloudClusterCreationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creations': ((json['creations'] as Array<any>).map(V1CreateCloudClusterResponseFromJSON)),
    };
}

export function V1ListCloudClusterCreationResponseToJSON(value?: V1ListCloudClusterCreationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creations': ((value.creations as Array<any>).map(V1CreateCloudClusterResponseToJSON)),
    };
}

