/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1PluginDTO } from './V1PluginDTO';
import {
    V1PluginDTOFromJSON,
    V1PluginDTOFromJSONTyped,
    V1PluginDTOToJSON,
} from './V1PluginDTO';

/**
 * 
 * @export
 * @interface V1ListPluginResponse
 */
export interface V1ListPluginResponse {
    /**
     * 
     * @type {Array<V1PluginDTO>}
     * @memberof V1ListPluginResponse
     */
    plugins: Array<V1PluginDTO>;
}

/**
 * Check if a given object implements the V1ListPluginResponse interface.
 */
export function instanceOfV1ListPluginResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "plugins" in value;

    return isInstance;
}

export function V1ListPluginResponseFromJSON(json: any): V1ListPluginResponse {
    return V1ListPluginResponseFromJSONTyped(json, false);
}

export function V1ListPluginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListPluginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plugins': ((json['plugins'] as Array<any>).map(V1PluginDTOFromJSON)),
    };
}

export function V1ListPluginResponseToJSON(value?: V1ListPluginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plugins': ((value.plugins as Array<any>).map(V1PluginDTOToJSON)),
    };
}

