/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Env } from './V1Env';
import {
    V1EnvFromJSON,
    V1EnvFromJSONTyped,
    V1EnvToJSON,
} from './V1Env';

/**
 * 
 * @export
 * @interface V1ListEnvResponse
 */
export interface V1ListEnvResponse {
    /**
     * 
     * @type {Array<V1Env>}
     * @memberof V1ListEnvResponse
     */
    envs: Array<V1Env>;
    /**
     * 
     * @type {number}
     * @memberof V1ListEnvResponse
     */
    total: number;
}

/**
 * Check if a given object implements the V1ListEnvResponse interface.
 */
export function instanceOfV1ListEnvResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "envs" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function V1ListEnvResponseFromJSON(json: any): V1ListEnvResponse {
    return V1ListEnvResponseFromJSONTyped(json, false);
}

export function V1ListEnvResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListEnvResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'envs': ((json['envs'] as Array<any>).map(V1EnvFromJSON)),
        'total': json['total'],
    };
}

export function V1ListEnvResponseToJSON(value?: V1ListEnvResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'envs': ((value.envs as Array<any>).map(V1EnvToJSON)),
        'total': value.total,
    };
}

