/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1AddonBaseStatus } from './V1AddonBaseStatus';
import {
    V1AddonBaseStatusFromJSON,
    V1AddonBaseStatusFromJSONTyped,
    V1AddonBaseStatusToJSON,
} from './V1AddonBaseStatus';

/**
 * 
 * @export
 * @interface V1ListEnabledAddonResponse
 */
export interface V1ListEnabledAddonResponse {
    /**
     * 
     * @type {Array<V1AddonBaseStatus>}
     * @memberof V1ListEnabledAddonResponse
     */
    enabledAddons: Array<V1AddonBaseStatus>;
}

/**
 * Check if a given object implements the V1ListEnabledAddonResponse interface.
 */
export function instanceOfV1ListEnabledAddonResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabledAddons" in value;

    return isInstance;
}

export function V1ListEnabledAddonResponseFromJSON(json: any): V1ListEnabledAddonResponse {
    return V1ListEnabledAddonResponseFromJSONTyped(json, false);
}

export function V1ListEnabledAddonResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListEnabledAddonResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabledAddons': ((json['enabledAddons'] as Array<any>).map(V1AddonBaseStatusFromJSON)),
    };
}

export function V1ListEnabledAddonResponseToJSON(value?: V1ListEnabledAddonResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabledAddons': ((value.enabledAddons as Array<any>).map(V1AddonBaseStatusToJSON)),
    };
}

