/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1RoleBase } from './V1RoleBase';
import {
    V1RoleBaseFromJSON,
    V1RoleBaseFromJSONTyped,
    V1RoleBaseToJSON,
} from './V1RoleBase';

/**
 * 
 * @export
 * @interface V1ListRolesResponse
 */
export interface V1ListRolesResponse {
    /**
     * 
     * @type {Array<V1RoleBase>}
     * @memberof V1ListRolesResponse
     */
    roles: Array<V1RoleBase>;
    /**
     * 
     * @type {number}
     * @memberof V1ListRolesResponse
     */
    total: number;
}

/**
 * Check if a given object implements the V1ListRolesResponse interface.
 */
export function instanceOfV1ListRolesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roles" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function V1ListRolesResponseFromJSON(json: any): V1ListRolesResponse {
    return V1ListRolesResponseFromJSONTyped(json, false);
}

export function V1ListRolesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListRolesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roles': ((json['roles'] as Array<any>).map(V1RoleBaseFromJSON)),
        'total': json['total'],
    };
}

export function V1ListRolesResponseToJSON(value?: V1ListRolesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roles': ((value.roles as Array<any>).map(V1RoleBaseToJSON)),
        'total': value.total,
    };
}

