/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ConfigTemplate } from './V1ConfigTemplate';
import {
    V1ConfigTemplateFromJSON,
    V1ConfigTemplateFromJSONTyped,
    V1ConfigTemplateToJSON,
} from './V1ConfigTemplate';

/**
 * 
 * @export
 * @interface V1ListConfigTemplateResponse
 */
export interface V1ListConfigTemplateResponse {
    /**
     * 
     * @type {Array<V1ConfigTemplate>}
     * @memberof V1ListConfigTemplateResponse
     */
    templates: Array<V1ConfigTemplate>;
}

/**
 * Check if a given object implements the V1ListConfigTemplateResponse interface.
 */
export function instanceOfV1ListConfigTemplateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "templates" in value;

    return isInstance;
}

export function V1ListConfigTemplateResponseFromJSON(json: any): V1ListConfigTemplateResponse {
    return V1ListConfigTemplateResponseFromJSONTyped(json, false);
}

export function V1ListConfigTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListConfigTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'templates': ((json['templates'] as Array<any>).map(V1ConfigTemplateFromJSON)),
    };
}

export function V1ListConfigTemplateResponseToJSON(value?: V1ListConfigTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'templates': ((value.templates as Array<any>).map(V1ConfigTemplateToJSON)),
    };
}

