/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1DefinitionBase } from './V1DefinitionBase';
import {
    V1DefinitionBaseFromJSON,
    V1DefinitionBaseFromJSONTyped,
    V1DefinitionBaseToJSON,
} from './V1DefinitionBase';

/**
 * 
 * @export
 * @interface V1ListDefinitionResponse
 */
export interface V1ListDefinitionResponse {
    /**
     * 
     * @type {Array<V1DefinitionBase>}
     * @memberof V1ListDefinitionResponse
     */
    definitions: Array<V1DefinitionBase>;
}

/**
 * Check if a given object implements the V1ListDefinitionResponse interface.
 */
export function instanceOfV1ListDefinitionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "definitions" in value;

    return isInstance;
}

export function V1ListDefinitionResponseFromJSON(json: any): V1ListDefinitionResponse {
    return V1ListDefinitionResponseFromJSONTyped(json, false);
}

export function V1ListDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListDefinitionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'definitions': ((json['definitions'] as Array<any>).map(V1DefinitionBaseFromJSON)),
    };
}

export function V1ListDefinitionResponseToJSON(value?: V1ListDefinitionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definitions': ((value.definitions as Array<any>).map(V1DefinitionBaseToJSON)),
    };
}

