/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1DetailUserResponse } from './V1DetailUserResponse';
import {
    V1DetailUserResponseFromJSON,
    V1DetailUserResponseFromJSONTyped,
    V1DetailUserResponseToJSON,
} from './V1DetailUserResponse';

/**
 * 
 * @export
 * @interface V1ListUserResponse
 */
export interface V1ListUserResponse {
    /**
     * 
     * @type {number}
     * @memberof V1ListUserResponse
     */
    total: number;
    /**
     * 
     * @type {Array<V1DetailUserResponse>}
     * @memberof V1ListUserResponse
     */
    users: Array<V1DetailUserResponse>;
}

/**
 * Check if a given object implements the V1ListUserResponse interface.
 */
export function instanceOfV1ListUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function V1ListUserResponseFromJSON(json: any): V1ListUserResponse {
    return V1ListUserResponseFromJSONTyped(json, false);
}

export function V1ListUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'users': ((json['users'] as Array<any>).map(V1DetailUserResponseFromJSON)),
    };
}

export function V1ListUserResponseToJSON(value?: V1ListUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'users': ((value.users as Array<any>).map(V1DetailUserResponseToJSON)),
    };
}

