/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1PermissionBase } from './V1PermissionBase';
import {
    V1PermissionBaseFromJSON,
    V1PermissionBaseFromJSONTyped,
    V1PermissionBaseToJSON,
} from './V1PermissionBase';
import type { V1UserProjectBase } from './V1UserProjectBase';
import {
    V1UserProjectBaseFromJSON,
    V1UserProjectBaseFromJSONTyped,
    V1UserProjectBaseToJSON,
} from './V1UserProjectBase';

/**
 * 
 * @export
 * @interface V1LoginUserInfoResponse
 */
export interface V1LoginUserInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof V1LoginUserInfoResponse
     */
    alias?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1LoginUserInfoResponse
     */
    createTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof V1LoginUserInfoResponse
     */
    disabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1LoginUserInfoResponse
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof V1LoginUserInfoResponse
     */
    lastLoginTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1LoginUserInfoResponse
     */
    name: string;
    /**
     * 
     * @type {Array<V1PermissionBase>}
     * @memberof V1LoginUserInfoResponse
     */
    platformPermissions: Array<V1PermissionBase>;
    /**
     * 
     * @type {{ [key: string]: Array<V1PermissionBase>; }}
     * @memberof V1LoginUserInfoResponse
     */
    projectPermissions: { [key: string]: Array<V1PermissionBase>; };
    /**
     * 
     * @type {Array<V1UserProjectBase>}
     * @memberof V1LoginUserInfoResponse
     */
    projects: Array<V1UserProjectBase>;
}

/**
 * Check if a given object implements the V1LoginUserInfoResponse interface.
 */
export function instanceOfV1LoginUserInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "disabled" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "lastLoginTime" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "platformPermissions" in value;
    isInstance = isInstance && "projectPermissions" in value;
    isInstance = isInstance && "projects" in value;

    return isInstance;
}

export function V1LoginUserInfoResponseFromJSON(json: any): V1LoginUserInfoResponse {
    return V1LoginUserInfoResponseFromJSONTyped(json, false);
}

export function V1LoginUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1LoginUserInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'createTime': (new Date(json['createTime'])),
        'disabled': json['disabled'],
        'email': json['email'],
        'lastLoginTime': (new Date(json['lastLoginTime'])),
        'name': json['name'],
        'platformPermissions': ((json['platformPermissions'] as Array<any>).map(V1PermissionBaseFromJSON)),
        'projectPermissions': json['projectPermissions'],
        'projects': ((json['projects'] as Array<any>).map(V1UserProjectBaseFromJSON)),
    };
}

export function V1LoginUserInfoResponseToJSON(value?: V1LoginUserInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'disabled': value.disabled,
        'email': value.email,
        'lastLoginTime': (value.lastLoginTime.toISOString()),
        'name': value.name,
        'platformPermissions': ((value.platformPermissions as Array<any>).map(V1PermissionBaseToJSON)),
        'projectPermissions': value.projectPermissions,
        'projects': ((value.projects as Array<any>).map(V1UserProjectBaseToJSON)),
    };
}

