/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1UserBase } from './V1UserBase';
import {
    V1UserBaseFromJSON,
    V1UserBaseFromJSONTyped,
    V1UserBaseToJSON,
} from './V1UserBase';

/**
 * 
 * @export
 * @interface V1LoginResponse
 */
export interface V1LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof V1LoginResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof V1LoginResponse
     */
    refreshToken: string;
    /**
     * 
     * @type {V1UserBase}
     * @memberof V1LoginResponse
     */
    user: V1UserBase;
}

/**
 * Check if a given object implements the V1LoginResponse interface.
 */
export function instanceOfV1LoginResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function V1LoginResponseFromJSON(json: any): V1LoginResponse {
    return V1LoginResponseFromJSONTyped(json, false);
}

export function V1LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1LoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'user': V1UserBaseFromJSON(json['user']),
    };
}

export function V1LoginResponseToJSON(value?: V1LoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
        'user': V1UserBaseToJSON(value.user),
    };
}

