/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1NameAlias } from './V1NameAlias';
import {
    V1NameAliasFromJSON,
    V1NameAliasFromJSONTyped,
    V1NameAliasToJSON,
} from './V1NameAlias';

/**
 * 
 * @export
 * @interface V1PipelineMetaResponse
 */
export interface V1PipelineMetaResponse {
    /**
     * 
     * @type {string}
     * @memberof V1PipelineMetaResponse
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof V1PipelineMetaResponse
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1PipelineMetaResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof V1PipelineMetaResponse
     */
    name: string;
    /**
     * 
     * @type {V1NameAlias}
     * @memberof V1PipelineMetaResponse
     */
    project: V1NameAlias;
}

/**
 * Check if a given object implements the V1PipelineMetaResponse interface.
 */
export function instanceOfV1PipelineMetaResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "project" in value;

    return isInstance;
}

export function V1PipelineMetaResponseFromJSON(json: any): V1PipelineMetaResponse {
    return V1PipelineMetaResponseFromJSONTyped(json, false);
}

export function V1PipelineMetaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PipelineMetaResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        'description': json['description'],
        'name': json['name'],
        'project': V1NameAliasFromJSON(json['project']),
    };
}

export function V1PipelineMetaResponseToJSON(value?: V1PipelineMetaResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'description': value.description,
        'name': value.name,
        'project': V1NameAliasToJSON(value.project),
    };
}

