/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1NameAlias } from './V1NameAlias';
import {
    V1NameAliasFromJSON,
    V1NameAliasFromJSONTyped,
    V1NameAliasToJSON,
} from './V1NameAlias';

/**
 * 
 * @export
 * @interface V1ProjectBase
 */
export interface V1ProjectBase {
    /**
     * 
     * @type {string}
     * @memberof V1ProjectBase
     */
    alias: string;
    /**
     * 
     * @type {Date}
     * @memberof V1ProjectBase
     */
    createTime: Date;
    /**
     * 
     * @type {string}
     * @memberof V1ProjectBase
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProjectBase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProjectBase
     */
    namespace: string;
    /**
     * 
     * @type {V1NameAlias}
     * @memberof V1ProjectBase
     */
    owner?: V1NameAlias;
    /**
     * 
     * @type {Date}
     * @memberof V1ProjectBase
     */
    updateTime: Date;
}

/**
 * Check if a given object implements the V1ProjectBase interface.
 */
export function instanceOfV1ProjectBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "createTime" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespace" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function V1ProjectBaseFromJSON(json: any): V1ProjectBase {
    return V1ProjectBaseFromJSONTyped(json, false);
}

export function V1ProjectBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ProjectBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'createTime': (new Date(json['createTime'])),
        'description': json['description'],
        'name': json['name'],
        'namespace': json['namespace'],
        'owner': !exists(json, 'owner') ? undefined : V1NameAliasFromJSON(json['owner']),
        'updateTime': (new Date(json['updateTime'])),
    };
}

export function V1ProjectBaseToJSON(value?: V1ProjectBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'createTime': (value.createTime.toISOString()),
        'description': value.description,
        'name': value.name,
        'namespace': value.namespace,
        'owner': V1NameAliasToJSON(value.owner),
        'updateTime': (value.updateTime.toISOString()),
    };
}

