/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1RunStatInfo
 */
export interface V1RunStatInfo {
    /**
     * 
     * @type {number}
     * @memberof V1RunStatInfo
     */
    fail: number;
    /**
     * 
     * @type {number}
     * @memberof V1RunStatInfo
     */
    success: number;
    /**
     * 
     * @type {number}
     * @memberof V1RunStatInfo
     */
    total: number;
}

/**
 * Check if a given object implements the V1RunStatInfo interface.
 */
export function instanceOfV1RunStatInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fail" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function V1RunStatInfoFromJSON(json: any): V1RunStatInfo {
    return V1RunStatInfoFromJSONTyped(json, false);
}

export function V1RunStatInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RunStatInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fail': json['fail'],
        'success': json['success'],
        'total': json['total'],
    };
}

export function V1RunStatInfoToJSON(value?: V1RunStatInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fail': value.fail,
        'success': value.success,
        'total': value.total,
    };
}

