/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelProjectRef } from './ModelProjectRef';
import {
    ModelProjectRefFromJSON,
    ModelProjectRefFromJSONTyped,
    ModelProjectRefToJSON,
} from './ModelProjectRef';
import type { V1StatisticInfo } from './V1StatisticInfo';
import {
    V1StatisticInfoFromJSON,
    V1StatisticInfoFromJSONTyped,
    V1StatisticInfoToJSON,
} from './V1StatisticInfo';
import type { V1SystemVersion } from './V1SystemVersion';
import {
    V1SystemVersionFromJSON,
    V1SystemVersionFromJSONTyped,
    V1SystemVersionToJSON,
} from './V1SystemVersion';

/**
 * 
 * @export
 * @interface V1SystemInfoResponse
 */
export interface V1SystemInfoResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1SystemInfoResponse
     */
    dexUserDefaultPlatformRoles?: Array<string>;
    /**
     * 
     * @type {Array<ModelProjectRef>}
     * @memberof V1SystemInfoResponse
     */
    dexUserDefaultProjects?: Array<ModelProjectRef>;
    /**
     * 
     * @type {boolean}
     * @memberof V1SystemInfoResponse
     */
    enableCollection: boolean;
    /**
     * 
     * @type {Date}
     * @memberof V1SystemInfoResponse
     */
    installTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1SystemInfoResponse
     */
    loginType: string;
    /**
     * 
     * @type {string}
     * @memberof V1SystemInfoResponse
     */
    platformID: string;
    /**
     * 
     * @type {V1StatisticInfo}
     * @memberof V1SystemInfoResponse
     */
    statisticInfo?: V1StatisticInfo;
    /**
     * 
     * @type {V1SystemVersion}
     * @memberof V1SystemInfoResponse
     */
    systemVersion: V1SystemVersion;
}

/**
 * Check if a given object implements the V1SystemInfoResponse interface.
 */
export function instanceOfV1SystemInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enableCollection" in value;
    isInstance = isInstance && "loginType" in value;
    isInstance = isInstance && "platformID" in value;
    isInstance = isInstance && "systemVersion" in value;

    return isInstance;
}

export function V1SystemInfoResponseFromJSON(json: any): V1SystemInfoResponse {
    return V1SystemInfoResponseFromJSONTyped(json, false);
}

export function V1SystemInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SystemInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dexUserDefaultPlatformRoles': !exists(json, 'dexUserDefaultPlatformRoles') ? undefined : json['dexUserDefaultPlatformRoles'],
        'dexUserDefaultProjects': !exists(json, 'dexUserDefaultProjects') ? undefined : ((json['dexUserDefaultProjects'] as Array<any>).map(ModelProjectRefFromJSON)),
        'enableCollection': json['enableCollection'],
        'installTime': !exists(json, 'installTime') ? undefined : (new Date(json['installTime'])),
        'loginType': json['loginType'],
        'platformID': json['platformID'],
        'statisticInfo': !exists(json, 'statisticInfo') ? undefined : V1StatisticInfoFromJSON(json['statisticInfo']),
        'systemVersion': V1SystemVersionFromJSON(json['systemVersion']),
    };
}

export function V1SystemInfoResponseToJSON(value?: V1SystemInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dexUserDefaultPlatformRoles': value.dexUserDefaultPlatformRoles,
        'dexUserDefaultProjects': value.dexUserDefaultProjects === undefined ? undefined : ((value.dexUserDefaultProjects as Array<any>).map(ModelProjectRefToJSON)),
        'enableCollection': value.enableCollection,
        'installTime': value.installTime === undefined ? undefined : (value.installTime.toISOString()),
        'loginType': value.loginType,
        'platformID': value.platformID,
        'statisticInfo': V1StatisticInfoToJSON(value.statisticInfo),
        'systemVersion': V1SystemVersionToJSON(value.systemVersion),
    };
}

