/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UpdateProjectRequest
 */
export interface V1UpdateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProjectRequest
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProjectRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProjectRequest
     */
    owner?: string;
}

/**
 * Check if a given object implements the V1UpdateProjectRequest interface.
 */
export function instanceOfV1UpdateProjectRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpdateProjectRequestFromJSON(json: any): V1UpdateProjectRequest {
    return V1UpdateProjectRequestFromJSONTyped(json, false);
}

export function V1UpdateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateProjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
    };
}

export function V1UpdateProjectRequestToJSON(value?: V1UpdateProjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'description': value.description,
        'owner': value.owner,
    };
}

