/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1WorkflowPolicyBinding } from './V1WorkflowPolicyBinding';
import {
    V1WorkflowPolicyBindingFromJSON,
    V1WorkflowPolicyBindingFromJSONTyped,
    V1WorkflowPolicyBindingToJSON,
} from './V1WorkflowPolicyBinding';

/**
 * 
 * @export
 * @interface V1UpdatePolicyRequest
 */
export interface V1UpdatePolicyRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePolicyRequest
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePolicyRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePolicyRequest
     */
    envName: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePolicyRequest
     */
    properties: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePolicyRequest
     */
    type: string;
    /**
     * 
     * @type {Array<V1WorkflowPolicyBinding>}
     * @memberof V1UpdatePolicyRequest
     */
    workflowPolicyBind: Array<V1WorkflowPolicyBinding>;
}

/**
 * Check if a given object implements the V1UpdatePolicyRequest interface.
 */
export function instanceOfV1UpdatePolicyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "envName" in value;
    isInstance = isInstance && "properties" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "workflowPolicyBind" in value;

    return isInstance;
}

export function V1UpdatePolicyRequestFromJSON(json: any): V1UpdatePolicyRequest {
    return V1UpdatePolicyRequestFromJSONTyped(json, false);
}

export function V1UpdatePolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdatePolicyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'description': json['description'],
        'envName': json['envName'],
        'properties': json['properties'],
        'type': json['type'],
        'workflowPolicyBind': ((json['workflowPolicyBind'] as Array<any>).map(V1WorkflowPolicyBindingFromJSON)),
    };
}

export function V1UpdatePolicyRequestToJSON(value?: V1UpdatePolicyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'description': value.description,
        'envName': value.envName,
        'properties': value.properties,
        'type': value.type,
        'workflowPolicyBind': ((value.workflowPolicyBind as Array<any>).map(V1WorkflowPolicyBindingToJSON)),
    };
}

