/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UpdateRoleRequest
 */
export interface V1UpdateRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRoleRequest
     */
    alias: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpdateRoleRequest
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the V1UpdateRoleRequest interface.
 */
export function instanceOfV1UpdateRoleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "alias" in value;
    isInstance = isInstance && "permissions" in value;

    return isInstance;
}

export function V1UpdateRoleRequestFromJSON(json: any): V1UpdateRoleRequest {
    return V1UpdateRoleRequestFromJSONTyped(json, false);
}

export function V1UpdateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'permissions': json['permissions'],
    };
}

export function V1UpdateRoleRequestToJSON(value?: V1UpdateRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'permissions': value.permissions,
    };
}

