/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UpdateDefinitionStatusRequest
 */
export interface V1UpdateDefinitionStatusRequest {
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateDefinitionStatusRequest
     */
    hiddenInUI: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateDefinitionStatusRequest
     */
    type: string;
}

/**
 * Check if a given object implements the V1UpdateDefinitionStatusRequest interface.
 */
export function instanceOfV1UpdateDefinitionStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hiddenInUI" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function V1UpdateDefinitionStatusRequestFromJSON(json: any): V1UpdateDefinitionStatusRequest {
    return V1UpdateDefinitionStatusRequestFromJSONTyped(json, false);
}

export function V1UpdateDefinitionStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateDefinitionStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hiddenInUI': json['hiddenInUI'],
        'type': json['type'],
    };
}

export function V1UpdateDefinitionStatusRequestToJSON(value?: V1UpdateDefinitionStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hiddenInUI': value.hiddenInUI,
        'type': value.type,
    };
}

