/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1UpdateApplicationTraitRequest
 */
export interface V1UpdateApplicationTraitRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateApplicationTraitRequest
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateApplicationTraitRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateApplicationTraitRequest
     */
    properties: string;
}

/**
 * Check if a given object implements the V1UpdateApplicationTraitRequest interface.
 */
export function instanceOfV1UpdateApplicationTraitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "properties" in value;

    return isInstance;
}

export function V1UpdateApplicationTraitRequestFromJSON(json: any): V1UpdateApplicationTraitRequest {
    return V1UpdateApplicationTraitRequestFromJSONTyped(json, false);
}

export function V1UpdateApplicationTraitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateApplicationTraitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'properties': json['properties'],
    };
}

export function V1UpdateApplicationTraitRequestToJSON(value?: V1UpdateApplicationTraitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'description': value.description,
        'properties': value.properties,
    };
}

