/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelWorkflowSpec } from './ModelWorkflowSpec';
import {
    ModelWorkflowSpecFromJSON,
    ModelWorkflowSpecFromJSONTyped,
    ModelWorkflowSpecToJSON,
} from './ModelWorkflowSpec';

/**
 * 
 * @export
 * @interface V1UpdatePipelineRequest
 */
export interface V1UpdatePipelineRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePipelineRequest
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePipelineRequest
     */
    description?: string;
    /**
     * 
     * @type {ModelWorkflowSpec}
     * @memberof V1UpdatePipelineRequest
     */
    spec?: ModelWorkflowSpec;
}

/**
 * Check if a given object implements the V1UpdatePipelineRequest interface.
 */
export function instanceOfV1UpdatePipelineRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpdatePipelineRequestFromJSON(json: any): V1UpdatePipelineRequest {
    return V1UpdatePipelineRequestFromJSONTyped(json, false);
}

export function V1UpdatePipelineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdatePipelineRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'spec': !exists(json, 'spec') ? undefined : ModelWorkflowSpecFromJSON(json['spec']),
    };
}

export function V1UpdatePipelineRequestToJSON(value?: V1UpdatePipelineRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alias': value.alias,
        'description': value.description,
        'spec': ModelWorkflowSpecToJSON(value.spec),
    };
}

