/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1WorkflowPolicyBinding
 */
export interface V1WorkflowPolicyBinding {
    /**
     * 
     * @type {string}
     * @memberof V1WorkflowPolicyBinding
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1WorkflowPolicyBinding
     */
    steps: Array<string>;
}

/**
 * Check if a given object implements the V1WorkflowPolicyBinding interface.
 */
export function instanceOfV1WorkflowPolicyBinding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "steps" in value;

    return isInstance;
}

export function V1WorkflowPolicyBindingFromJSON(json: any): V1WorkflowPolicyBinding {
    return V1WorkflowPolicyBindingFromJSONTyped(json, false);
}

export function V1WorkflowPolicyBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1WorkflowPolicyBinding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'steps': json['steps'],
    };
}

export function V1WorkflowPolicyBindingToJSON(value?: V1WorkflowPolicyBinding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'steps': value.steps,
    };
}

