/* tslint:disable */
/* eslint-disable */
/**
 * Kubevela api doc
 * Kubevela api doc
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: feedback@mail.kubevela.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BcodeBcode,
  V1SystemInfoRequest,
  V1SystemInfoResponse,
} from '../models/index';
import {
    BcodeBcodeFromJSON,
    BcodeBcodeToJSON,
    V1SystemInfoRequestFromJSON,
    V1SystemInfoRequestToJSON,
    V1SystemInfoResponseFromJSON,
    V1SystemInfoResponseToJSON,
} from '../models/index';

export interface UpdateSystemInfoRequest {
    body: V1SystemInfoRequest;
}

/**
 *
 */
export class SystemInfoApi extends runtime.BaseAPI {

    /**
     */
    async getSystemInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SystemInfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/system_info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SystemInfoResponseFromJSON(jsonValue));
    }

    /**
     */
    async getSystemInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SystemInfoResponse> {
        const response = await this.getSystemInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateSystemInfoRaw(requestParameters: UpdateSystemInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SystemInfoResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateSystemInfo.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/system_info`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: V1SystemInfoRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SystemInfoResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateSystemInfo(requestParameters: UpdateSystemInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SystemInfoResponse> {
        const response = await this.updateSystemInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
